### ISSUE TITLE
I want to install this pkg. but, I don't know how to do well 

### ISSUE THREAD

**Issue by DoranLyong** [RIVeR-Lab/epos_hardware#1]
Hi.  May I ask your help?

I want to install this  in my computer to use EPOS motor controller with ROS  .
Because I need  for my undergraduate course graduation
Maybe I thought, I installed EPOS Command Library well.

Because, When I test  ' $sudo ./HelloEposCmd -n 2 ' 
![2015-08-17 15 30 53](https://cloud.githubusercontent.com/assets/13333380/9299260/faa83afc-44f4-11e5-84c7-2e7416c9f5b9.png)
The result seems well done.  

But, My problem is I don't know the progress on installing this ROS node pkg..

Just Do I need to copy this git like 

$ cd ~/catkin_ws/src/
$ git clone https://github.com/RIVeR-Lab/epos_hardware.git
$ cd epos_hardware

........
and then?? What I need to do? 

My condition is  64 bit ,Unbuntu, ROS, indigo

**Comment by maztentropy** [comment]
Did you try just typing 'sudo apt-get install ros-indigo-epos-hardware'?

**Comment by DoranLyong** [comment]
Ah T.T   Thank you.  I 'm really waiting your answer.    

Yes, I tried .    But I got msg that " can not find  package"

![2015-09-01 17 02 08](https://cloud.githubusercontent.com/assets/13333380/9599014/34224d90-50cb-11e5-9e9f-7142675705cb.png)

So, I have tried to clone this git src and make .  I don't know how to solve this . 

Do I need to add another repositroy address? 

I also did   'sudo apt get update && sudo apt get upgrade

**Comment by dysoul** [comment]
Uhm...  I tried it in another my computer  and It was installed .  I don't know what is different each other.   

anyway,  Is it done only if using  'sudo apt-get install  ros-indigo-epos-hardware ??  

Can I just use it????    I want to use ' step mode ' . 
I don't understand  how Can I configure with it. 

$ rosrun epos_hardware epos_hardware_node motor_name1/position_regulator   

??Do I have to write like that?

**Comment by DoranLyong** [comment]
Uhm... I tried it in another my computer and It was installed . I don't know what is different each other.

anyway, Is it done only if using 'sudo apt-get install ros-indigo-epos-hardware ??

Can I just use it???? I want to use ' step mode ' .
I don't understand how Can I configure with it.

$ rosrun epos_hardware epos_hardware_node motor_name1/position_regulator

??Do I have to write like that?

**Comment by maztentropy** [comment]
I am not sure if this is the proper place for this but you basically need to read and understand everything here: http://wiki.ros.org/epos_hardware

It is indeed installed only by typing that line if everything goes well. About the usage you need to know how ROS and more specifically ros_control works in order to make it work. You can try to run the example provided by the author by typing: 'roslaunch epos_hardware example.launch'.

**Comment by mitchellwills** [comment]
If you are looking for some documentation on the package maztentropy is right that you can find it here. If you are simply looking to control the motor and don't have a reason to use ROS than I suggest you use Maxon's Library directly (http://www.maxonmotorusa.com/medias/sys_master/root/8815100788766/EPOS-Command-Library-En.pdf). Especially if you have not used ROS or ros_control before and you don't need to use them.
Also the reason why you were probably unable to install it on one of your computers was that you had not followed the ROS setup instructions.
