### ISSUE TITLE
Kinetic-devel branch

### ISSUE THREAD

**Issue by giusebar** [RIVeR-Lab/epos_hardware#16]
Hi,

I would like to propose the addition of kinetic-devel branch to this repository.
I have made a fork and did the necessary changes to make the code work in ROS Kinetic. 

Branch:
https://github.com/shadow-robot/epos_hardware/tree/F_kinetic_branch

Commit:
https://github.com/shadow-robot/epos_hardware/commit/ffbb6fdf3ce36800e1205ac72df039f9075c4cb5

With this addition I'm successfully running an EPOS2 70/10 in Kinetic.
If you create the new branch I can make a PR with the necessary changes.

Cheers,
Giuseppe

**Comment by velinddimitrov** [comment]
I have created the kinetic devel branch. Feel free to PR to it and I will approve the PR.

**Comment by velinddimitrov** [comment]
Merged
