### ISSUE TITLE
Motor communication fails

### ISSUE THREAD

**Issue by maztentropy** [RIVeR-Lab/epos_hardware#2]
I have tried to establish communications using the provided example.launch file but it apparently cannot communicate with the motor. Other executable like get_state and list_devices seem to communicate with my motor properly though. I have opened a ROS answers topic about it: 

http://answers.ros.org/question/216315/help-using-epos_hardware/

Could there be a problem in the way the serial number is handled internally?

**Comment by mitchellwills** [comment]
I added a response to your question. The serial number you have is probably in decimal. Try converting it to hex with the 0x prefix and see if that works. Feel free to add a PR to support both formats of SN

**Comment by grafoteka** [comment]
Hi @mitchellwills I'm having the same error as @maztentropy.
I have try changing the serial number that "list devices" program indicates. With 0x before and without it.
