### ISSUE TITLE
fatal error: transmission_interface/robot_transmissions.h

### ISSUE THREAD

**Issue by grafoteka** [RIVeR-Lab/epos_hardware#6]
Hello! 
I'm trying to compile your package, but when I do catkin_make I have the next error:

`In file included from /home/erix/catkin_ws/src/epos_hardware/epos_hardware/src/util/epos_manager.cpp:1:0:
/home/erix/catkin_ws/src/epos_hardware/epos_hardware/include/epos_hardware/epos_manager.h:8:56: fatal error: transmission_interface/robot_transmissions.h: No such file or directory
compilation terminated.`

Is any directory missing?

Thank you for your answer

Regards, Jorge

**Comment by velinddimitrov** [comment]
Do you have ros control installed? (sudo apt-get install ros-indigo-ros-control ros-indigo-ros-controllers)

#7 here: http://wiki.ros.org/ros_control?distro=indigo

**Comment by grafoteka** [comment]
Thank you for your reply @velinddimitrov. Maybe the problem was because I was on ROS Hydro, instead I had installed the ros-control and controllers packages.

Now with ROS Kinetic this problem doesn't appear.
